- .github/workflows/deploy.yml
- ansible/inventory
- ansible/inventory.yml
This is easier to decipher and maintain.
> Reformat the inventory as YAML

- setup.py
- watch/settings.py
Update for https://github.com/ResonantGeoData/ResonantGeoData/pull/492
Adds `crum.CurrentRequestUserMiddleware` for the upstream changes that track users creating files
> Add CRUM middleware

- rgd-watch-client/rgd_watch_client/plugin.py
- tox.ini
- watch/core/filters.py
- watch/core/tests/test_client.py
> Update client with new methods

- django/src/rdwatch/serializers/__init__.py
- django/src/rdwatch/serializers/site.py
- django/src/rdwatch/urls.py
- django/src/rdwatch/views/__init__.py
- django/src/rdwatch/views/site.py
Adds a serializer and a view for `Site`.
> Add Site endpoint

- django/src/rdwatch/db/functions.py
- django/src/rdwatch/urls.py
- django/src/rdwatch/views/__init__.py
- django/src/rdwatch/views/site_tile.py
Exposes a [Mapbox Vector Tile](https://docs.mapbox.com/data/tilesets/guides/vector-tiles-introduction/) endpoint for the `Site` geometry.
> Add vector tile endpoint

- .devcontainer/devcontainer.json
- .github/workflows/ci.yaml
- django/.flake8
- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/models/prediction_configuration.py
- django/src/rdwatch/models/saliency.py
- django/src/rdwatch/models/saliency_tile.py
- django/src/rdwatch/models/satellite_image.py
- django/src/rdwatch/models/site.py
- django/src/rdwatch/models/tracking_configuration.py
- vscode.code-workspace
Although the package is cool, I was finding [`prospector`](https://prospector.landscape.io/en/master/index.html) very slow. Switching to `flake8` makes linting much faster.
> Use `flake8` instead of `prospector`

- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/server/settings.py
Reverts ResonantGeoData/RD-WATCH#84
> Revert "Add `django-extensions`"

- django/src/rdwatch/db/functions.py
- django/src/rdwatch/urls.py
- django/src/rdwatch/views/__init__.py
- django/src/rdwatch/views/saliency_tile.py
- docker/services/postgresql/initdb.sh
> Add raster tile endpoint

- cli/src/rdwatch_cli/movie.py
- django/src/rdwatch/urls.py
- django/src/rdwatch/utils/satellite_bands.py
- django/src/rdwatch/views/__init__.py
- django/src/rdwatch/views/tile.py
Also adds an additional server endpoint to facilitate this.
> Accept datetime range instead of individual timestamps for CLI `movie` command

- cli/.flake8
- cli/poetry.lock
- cli/pyproject.toml
- cli/src/rdwatch_cli/__init__.py
- cli/src/rdwatch_cli/config.py
- cli/src/rdwatch_cli/image.py
- cli/src/rdwatch_cli/login.py
- cli/src/rdwatch_cli/movie.py
- cli/src/rdwatch_cli/validators.py
- django/src/rdwatch/fixtures/lookups.json
- django/src/rdwatch/urls.py
- django/src/rdwatch/utils/satellite_bands.py
- django/src/rdwatch/utils/stac_search.py
- django/src/rdwatch/views/__init__.py
- django/src/rdwatch/views/tile.py
- vscode.code-workspace
This draft PR tracks the progress of creating a script to make a movie specified by:
- a bounding box
- a series of timestamps
The command (and equivalent Python function) can be used as:
```bash
rdwatch movie \
--bbox $XMIN $YMIN $XMAX $YMAX \
--time $ISOTIMESTAMP_1 \
--time $ISOTIMESTAMP_2 \
--time $ISOTIMESTAMP_3 \
--time $ISOTIMESTAMP_4 \
--time $ISOTIMESTAMP_N
```
To do:
> Add script to make movie of a bounding box

- django/src/rdwatch/server/settings.py
I forgot to commit this file in #105 :sweat_smile:
> Add missing setting for `django_filters`

- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
> Paginate model runs with infinite scrolling list

- INGESTION.md
- django/src/rdwatch/serializers/hyper_parameters.py
I had forgotten to include the `title` field in the `HyperParametersWriteSerializer`. Probably would be a good idea to add tests to these endpoints at some point.
> Ingest fix

- vue/src/mapstyle/rdwatchtiles.ts
> Change colors for some outlines + make ground truth outline thicker

- vue/src/client/models/ModelRun.ts
- vue/src/components/MapLibre.vue
- vue/src/components/ModelRunList.vue
- vue/src/interactions/popup.ts
- vue/src/mapstyle/rdwatchtiles.ts
- vue/vite.config.ts
Creates a small popup with the ID of each item under the cursor.  Color is indexed by the current annotation color.
https://user-images.githubusercontent.com/61746913/214079352-dbdec2cf-52f2-459b-8ebf-139e54cecf07.mp4
> Popup ID info

- vue/src/components/FilterSelect.vue
- vue/src/components/MapLibre.vue
- vue/src/components/SettingsPanel.vue
- vue/src/components/SideBar.vue
- vue/src/interactions/fillPatterns.ts
- vue/src/mapstyle/rdwatchtiles.ts
- vue/src/store.ts
- vue/tailwind.config.cjs
Also adjusted CSS on the region/Performer dropdowns to make them a bit easier to use.
Determine where the toggle is for this?
Is it at the ModelRun level or at a global level?
> Basic Fill Patterns

- vue/src/components/FilterSelect.vue
- vue/src/components/MapLibre.vue
- vue/src/components/ModelRunList.vue
- vue/src/components/SettingsPanel.vue
- vue/src/components/SideBar.vue
- vue/src/interactions/fillPatterns.ts
- vue/src/interactions/popup.ts
- vue/src/mapstyle/index.ts
- vue/src/mapstyle/naturalearth.ts
- vue/src/mapstyle/openmaptiles.ts
- vue/src/mapstyle/rdwatchtiles.ts
- vue/src/store.ts
- vue/vite.config.ts
Updates the pattern settings so they persist between opening and closing the settings location.
> Fix Pattern Settings Persistence

- django/src/rdwatch/urls.py
- django/src/rdwatch/views/__init__.py
- django/src/rdwatch/views/site_model.py
Adds a new endpoint for ingesting `site-summary` JSONs.
> site-summary ingest endpoint

- django/src/rdwatch/views/model_run.py
Previously, we were returning the number of `regions` as the `count` field for the model runs endpoint. This PR fixes this to return the actual number of _model runs_ instead.
> Fix `count` field in model runs list endpoint

- vue/src/components/FilterSelect.vue
- vue/src/components/MapLibre.vue
- vue/src/components/ModelRunDetail.vue
- vue/src/components/ModelRunList.vue
- vue/src/components/SettingsPanel.vue
- vue/src/components/SideBar.vue
- vue/src/components/TimeSlider.vue
- vue/src/components/filters/RegionFilter.vue
- vue/src/interactions/popup.ts
- vue/src/store.ts
Fixes the siteId label to display: <region>_<site_number>
Fixes the cancellation of promise when scrolling to the bottom of the list.
>  SiteId label and cancelable promise correction for loading.

- vue/src/interactions/satelliteLoading.ts
Quick fix to the loading to reset state when changing image timestamp or turning satellite images on/off.
> improve satellite loading toggle

- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/server/settings.py
This will allow us to debug issues in production easier.
> Install `django-extensions`

- Dockerfile
I think this will fix the deploy issues. cc @BryonLewis
> Copy venv in final docker build stage

- django/src/rdwatch/tasks/__init__.py
Removes the duplicate logic from the site fetching (maybe this was causing some timing issues).
> remove duplicate logic from image fetching task and add percent_black

- django/src/rdwatch/views/model_run.py
I believe this should resolve the region filter not working properly.
> Change region filter from OR to AND

- django/src/rdwatch/urls.py
> Remove deprecated non-trailing slash endpoints

- django/src/rdwatch/views/vector_tile.py
- vue/src/components/imageViewer/ImageViewer.vue
- vue/src/mapstyle/annotationStyles.ts
> Use direct string values for labels instead of strings

- django/src/rdwatch/schemas/region_model.py
- django/src/rdwatch/schemas/site_model.py
- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/site_observation.py
- vue/src/client/services/ApiService.ts
- vue/src/components/ImagesDownloadDialog.vue
There were some proposals that had a siteId of AE_R001_99999104 which were causing issues on posting.  This will update the code to accept the higher numbers.
> Allow for higher digit number proposals

- django/src/rdwatch/fixtures/lookups.json
Partially addresses https://smartgitlab.com/TE/RD-WATCH/-/issues/8.
> Rename "Test and Evaluation Team" to "Ground Truth" in UI

- django/src/rdwatch/schemas/site_model.py
Closes https://smartgitlab.com/TE/RD-WATCH/-/issues/37.
> Update site model schema to align with new changes

- django/src/rdwatch/models/site_evaluation.py
- django/src/rdwatch_scoring/views/vector_tile.py
This got dropped somehow from #306.
> Adding iMERIT as a valid originator for ground truth

- django/src/rdwatch/tasks/__init__.py
- django/src/rdwatch/views/model_run.py
- django/src/rdwatch_scoring/tasks/__init__.py
- django/src/rdwatch_scoring/views/model_run.py
Iterating over every `SiteEvaluation` inside an endpoint can potentially spike response times. In extreme cases, this tends to cause gateway timeout errors on the AWS deployment if run on a model run with thousands (or more) of associated site evaluations. To fix this, I moved most of the cancellation logic into a celery task.
> Optimize cancellation endpoint to avoid timeouts

- .github/workflows/cd.yaml
I think this will fix the failing CI on `main`.
> Add `apt-get update` to cli build

- django/src/rdwatch/views/site_image.py
- django/src/rdwatch_scoring/views/site_image.py
Allows for null labels in the SiteObservations.  There were specific sites which had this value that were failing before.
> fix null site obs labels

- docker-compose.override.yaml
- tileserver/devServer.mjs
- tileserver/package-lock.json
- tileserver/rgd.mjs
- vue/src/components/imageViewer/ImageViewer.vue
- vue/src/interactions/editPolygon.ts
- Adds vector-server for docker compose development to locally have node.js based tileserver running.
- Updates the `randomKey` parameter to work properly with the editing of polygons in the proposal view.
> Docker Vector-Tiler Server Updates

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
- django/poetry.lock
- django/pyproject.toml
- django/tox.ini
@BryonLewis can you test this locally and see if it works for you? It appears to work for me, but I'm never sure if my docker container is actually reinstalling dependencies or using some cache.
> Switch to cpu-only version of pytorch, fix poetry/tox integration

- vue/src/client/services/ApiService.ts
> Fix missing trailing slashes

- django/src/rdwatch_scoring/models/site.py
- tileserver/scoring.mjs
- vue/src/mapstyle/rdwatchtiles.ts
This PR adds support for point-based annotations to the scoring mode.
TODO:
> Support point annotations in scoring view

- tileserver/package-lock.json
- tileserver/package.json
> Bump version of tileserver node package

- vue/src/components/imageViewer/ImageEditorDetails.vue
- Start date wouldn't properly close the dialog and update the time
- Also updated the currentDate to properly reflect the date in the slider
> Fix Start Date Editor

- django/poetry.lock
- django/pyproject.toml
This makes some improvements/cleanups to the `pyproject.toml` that I noticed when working on #396 but didn't think were appropriate to include in that PR.
> Misc `pyproject.toml` fixes/cleanup

- django/src/rdwatch_scoring/router.py
- django/src/rdwatch_scoring/views/model_run.py
- django/src/rdwatch_scoring/views/site_evaluation.py
- django/src/rdwatch_scoring/views/site_image.py
- django/src/rdwatch_scoring/views/site_observation.py
This PR is set to merge into #392 and serves as the rest of my review for that PR. For the most part it makes changes such as using convenience methods provided by Django/Ninja such as `get_object_or_404`, or adding query params for `GET` endpoints as function arguements instead of pulling them out of the `request` object ([relevant docs for that](https://django-ninja.dev/guides/input/query-params/)).
I haven't looked at any of the vector tile code yet, I will do that next and port them to the node server.
> Proposals scoring review

- INGESTION.md
Updates ingest docs in accordance with #407 and #396
> Update ingest docs

- vue/vite.config.ts
Small change to fix the static view when redirected to login when in local dev.
> fix admin view when redirected in local dev

- .github/workflows/cd.yaml
This will silence the warnings, for example here https://github.com/ResonantGeoData/RD-WATCH/actions/runs/10324557560
> Update deprecated action

- vue/src/views/SmartFlow.vue
- vue/vite.config.ts
> Remove unused variable from vite.config.ts

- scripts/loadGroundTruth.py
I added this change in order to diagnose the problem related to #484.
> Show error details on model run creation failure

- rdwatch/core/views/model_run.py
- rdwatch/core/views/satellite_fetching.py
- rdwatch/scoring/views/satellite_fetching.py
I feel like I'm writing this line of code for the 6th or 7th time now.
I think it got duplicated in the PRs and merging to main over the past few days.
> Fix Model Run downloads

- poetry.lock
- pyproject.toml
Updates all dev/test dependencies to the latest version.
> Upgrade python dev/test dependencies

- rdwatch/scoring/views/model_run.py
When using the downloading for a site and no images are present the current query wouldn't return that site was downloading.  This would prevent the UI from polling the downloading endpoint to check and see if images are currently being downloaded.
This was because we did a query on the SiteImages with a subquery for SatelliteFetching.  This meant that if a site had 0 images downloaded and had no SIteImages rows it wouldn't indicate that the SatelliteFetching was in progress.
I've added a separate query for the SatelliteFetching by ModelRun that will get that images are downloading even for sites that have 0 images downloaded.
> Fix image downloading for scoring when No images are present

- rdwatch/scoring/views/satellite_fetching.py
Fixes https://kitware-data.sentry.io/issues/6078296646/?alert_rule_id=15484485&alert_type=issue&notification_uuid=4cb70819-4e53-43b8-ba6e-7cf19fe3d736&project=4508054265724928&referrer=issue_alert-slack
> Fix `UnboundLocalError`

- vue/src/components/animation/AnimationDownloadDialog.vue
- vue/src/components/imageViewer/ImageViewer.vue
Make sure the image viewer setting rescale and rescale border are propagated into the animation exporting.
> fix rescale image export
