- ansible/inventory.yml
Also remove the "sh -c" wrapper and run the ProxyCommand directly.
> Ensure that ansible_ssh_common_args is interpreted as a single argument

- ansible/inventory.yml
The SSH config docs specify that using `=` to delimit option values will help avoid whitespace escaping issues.
> Use an alternate form of SSH options to prevent quote issues

- rgd-watch-client/rgd_watch_client/__init__.py
Closes #47
This new method should be used in place of `create_rgd_client`.
> Add create_watch_client method

- .github/workflows/data_ingest.yml
- rgd-watch-client/rgd_watch_client/__init__.py
- rgd-watch-client/rgd_watch_client/plugin.py
- rgd-watch-client/setup.py
- scripts/watch_helpers/__init__.py
- setup.py
- watch/core/tests/test_client.py
- watch/core/tests/test_stac.py
A dry run test of iterating over the STAC Catalogs. Both Sentinel and Landsat catalogs error after 10000 items, but the Landsat one gives an error message:
```
search_phase_execution_exception: [illegal_argument_exception] Reason: Result window is too large, from + size must be less than or equal to: [10000] but was [10010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.
```
The S3 static catalogs work fine.
----
This seems relevant: https://github.com/sat-utils/sat-api/issues/225
> Dry run of STAC Catalog iteration

- django/src/rdwatch/db/functions.py
Forgot to cache-bust while working on #86.
This ensures the tiles are always 512-by-512px and disables transparency.
> Fix raster tile endpoint

- django/pyproject.toml
- django/src/rdwatch/management/commands/ingest.py
- django/src/rdwatch/migrations/0002_initial.py
- django/src/rdwatch/models/region.py
- django/src/rdwatch/models/satellite_image.py
- django/src/rdwatch/serializers/server_status.py
- django/src/rdwatch/urls.py
- django/src/rdwatch/views/server_status.py
- django/src/rdwatch/views/site.py
- django/src/rdwatch/views/tile.py
- docker-compose.yaml
- vscode.code-workspace
- **Fix MyPy cache location in VS Code**: MyPy in VS Code needs its own cache directory. See
https://stackoverflow.com/a/73617677.
- **Persist IPython history in development container**: IPython is popular enough that adding a persistent store of its readline entries makes sense.
- **Order imports to put `rdwatch` in its own section**: I found looking for it in the Django section a bit tiresome
> Miscellaneous development environment update

- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/views/site_evaluation.py
Closes #103
Uses [`django-filter`](https://django-filter.readthedocs.io/) to add filtering by timestamp range to the site evaluations endpoint.
The user can specify one or both of `timestamp_before` and `timestamp_after` as query params to the site evaluations endpoint to filter by date/time range. Uses the `DateTimeFromToRangeFilter`, docs are here https://django-filter.readthedocs.io/en/stable/ref/filters.html#datetimefromtorangefilter
> Filter `SiteEvaluations` by timestamp

- cli/pyproject.toml
- cli/src/rdwatch_cli/image.py
Geospatial coordinates were incorrectly being transformed to display coordinates.
> Fix CLI spatial transform

- django/src/rdwatch/serializers/site_evaluation.py
- django/src/rdwatch/server/settings.py
- django/src/rdwatch/views/site_evaluation.py
Closes #89 
Unfortunately, DRF's default pagination mechanism doesn't completely work here. DRF's `paginate_queryset` method returns a `list` instead of a `QuerySet`, and thus is intended to be called after all other queries have been made. Unfortunately, the end result of the queries made in the site evaluations endpoint is not a `QuerySet` but a `dict`, due to the use of `.aggregate()`. So, there doesn't appear to be a way to use DRF's native pagination methods here; instead, I've dropped down a level to Django's native `Paginator`, which the DRF one uses under the hood. 
I went ahead and configured pagination for DRF anyway in `settings.py`, and also refer to the `PAGE_SIZE` setting in the manual pagination code I wrote so it will be consistent with any DRF-paginated endpoints we have …
> Paginate Site Evaluations endpoint

- django/src/rdwatch/utils/worldview_processed/raster_tile.py
- django/src/rdwatch/utils/worldview_processed/satellite_captures.py
- django/src/rdwatch/utils/worldview_processed/stac_search.py
- django/src/rdwatch/views/tile.py
The unprocessed WorldView imagery is close to being complete, but is not orthorectified. As a stop-gap, we'll use processed WorldView imagery without pan-sharpening.
> Ortho-rectified WorldView imagery

- django/src/rdwatch/views/site_evaluation.py
A limit of "0" results in essentially no limit. Rather than handling this as a completely separate case, I just default to a really big integer when providing a limit of "0". This results in a really small diff, but may be confusing later on. @mvandenburgh, let me know if you have a better way of doing this.
> Allow setting page size

- django/src/rdwatch/views/site_model.py
Ingest silently failed by creating empty geometries when an [observation](https://smartgitlab.com/TE/standards/-/wikis/Site-Model-Specification#observation-feature) was a **Polygon** rather than a **MultiPolygon**.
This PR adds simple validation of the type of geometries to avoid this.
> Validate GeoJSON type of sites and observations

- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
Scrolling to the bottom of the list was possible, but extended beyond the screen. This PR switches to using Flexbox for the sidebar which seems to have a better handling of height calculation.
Before (scrolled to bottom) |  After (scrolled to bottom)
:-:|:-:
> Fix sidebar scrolling

- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
- vue/src/mapstyle/rdwatchtiles.ts
- vue/src/store.ts
Changes in this PR:
- Currently, when no model runs are selected in the UI, we render the tiles for _all_ of them. This PR changes this behavior to only render tiles for the selected model runs; i.e. if no model runs are selected, no tiles will be rendered.
- Remove the "Ground Truth" toggle. We discussed removing this before because it causes a lot of confusion and doesn't always make sense. Instead, the user can simply toggle the "Ground Truth" model run on/off in sidebar.
- _If a region is currently selected_, don't do any camera zooming when model runs are selected/deselected.
- Add UI toggle for "Site Outlines", and turn it off by default.
> UI Improvements

- django/src/rdwatch/views/model_run.py
- vue/src/client/models/ModelRunList.ts
- vue/src/components/ModelRunList.vue
This attempts to limit the amount of polygons that we're asking PostGIS to dynamically calculate a bounding box for in the model runs listing endpoint. If the user doesn't supply a region to filter by, the server will now *not* send back a bounding box to avoid an expensive PostGIS query across every polygon in the system.
> Fix performance issue in ModelRun listing endpoint

- docker-compose.yaml
- template.env
- vue/src/mapstyle/index.ts
- vue/src/mapstyle/naturalearth.ts
- vue/src/mapstyle/openmaptiles.ts
- vue/vite.config.ts
Switches the front-end to using an environment variable for the tile server instead of the hardcoded URLS.
Note this will need to be set during the build process so that the production build has the proper variable.
I made it default to the new URL if it can't find the env anyways.
ALSO:
```
VITE_TILE_SERVER_URL="https://basemap.kitware.watch"
```
Will need to be added to the .env file.
> Environment Variable Tile Server

- vue/src/components/ModelRunList.vue
The previous issue can be replicated by (on previous code):
Loading the dataset:
Select any region and then select the first model run in that region.
Next clear the region filter using the X in the dropdown and then select any model run which isn't the same as step 1.
Toggling off and on other regions will now cause the camera to get into a weird state where it may not properly zoom out to the entire world or zoom in the proper region.
The update will clear out the list each time the performer/region is changed.  This means each time the filter is updated you start from the beginning.  So the zooming and state shouldn't get into its weird state.
> Reset Configuration Ids when Perform/Region filter changes.

- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/api.py
- django/src/rdwatch/schemas/region_model.py
- django/src/rdwatch/schemas/site_model.py
- django/src/rdwatch/urls.py
- django/src/rdwatch/views/site_model.py
Currently, the ingest API returns 500 errors if an invalid site or region model JSON is posted. To fix this, we could catch these errors, format them in a useful way, and send them back in the endpoint response.
There's also another option. We're currently using `pydantic` to parse and validate these JSONs. `django-ninja` uses pydantic models for request/response serialization, and will automatically handle validation errors and send back an appropriate response for us, without needing any manual exception handling. So, I used this as an opportunity to convert the two ingest endpoints from DRF to django-ninja. The nice thing is that the rest of the endpoints can continue to use DRF or Django views, and we can convert those piecemeal over to `django-ninja` when we have time.
With these …
> Improved ingest error messages

- .github/workflows/ci.yaml
- DEVELOPMENT.md
- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/tests/conftest.py
- django/src/rdwatch/tests/test_ingest.py
- django/tox.ini
Configures `pytest` and `pytest-django`, and adds a single test for ingest.
There's definitely more aspects of the system that need to be tested, this is just a start to get everything in place we need to be able to write more tests easily in the future.
> Configure `pytest` and add test for ingest

- .github/workflows/cd.yaml
This prevents a race condition where two PRs are merged almost at the same time. In a case like that, it's possible the older PR's docker image build will complete *after* the newer PR's build, which would cause it to overwrite the new image on GHCR.
https://docs.github.com/en/actions/using-jobs/using-concurrency
> Configure concurrency for deployment workflow

- django/src/rdwatch/migrations/0005_alter_siteobservation_geom.py
- django/src/rdwatch/models/site_observation.py
- django/src/rdwatch/schemas/region_model.py
- django/src/rdwatch/schemas/site_model.py
- django/src/rdwatch/tests/conftest.py
- django/src/rdwatch/tests/test_ingest.py
- django/src/rdwatch/views/site_model.py
This PR:
- Fixes some incorrect usage of Pydantic validation that was resulting in some 500 errors in the ingest endpoints (https://github.com/ResonantGeoData/RD-WATCH/pull/165/commits/afaeb292b830356261b4c05be89def7c85f8a0fc)
- Improves the error messages returned when a user attempts to ingest an invalid site/region model json (https://github.com/ResonantGeoData/RD-WATCH/pull/165/commits/aed6702733ab29ddc854195189cd26f6695f7518)
- Makes the parsing of comma-separated lists during site model ingest cleaner by casting them to a list of strings at the start of ingestion (https://github.com/ResonantGeoData/RD-WATCH/pull/165/commits/08ae93cbb84defb8d78f05cbbe46f0ac3dac6e9c)
- Removes support for comma-separated list for region models (these are not supported by the spec) …
> Fix errors in site model ingest

- django/src/rdwatch/models/region.py
I didn't update this properly when we moved these endpoints from DRF to ninja, which is causing 500 errors to get thrown instead of 400.
> Use django-ninja `ValidationError` instead of DRF

- Dockerfile
- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/__init__.py
- django/src/rdwatch/celery.py
- django/src/rdwatch/server/settings.py
- django/src/rdwatch/tasks/__init__.py
- docker-compose.yaml
This PR
1) Installs celery and configures it in the rdwatch django app. Since we're already using Redis for caching, I just used that existing instance as the broker instead of configuring a new one such as RabbitMQ.
2) Adds a `celery` container to our docker compose dev config.
2) Refactors our docker build process to install `poetry` using python `pip` instead of `apt`, since the `python3-poetry` package on `apt` is outdated and doesn't have the needed CLI options.
3) Refactors the docker compose `django` service to build the image locally instead of always pulling it from ghcr.
- @BryonLewis do you have any thoughts/objections to this? My thinking is that it's better to do it this way to facilitate making changes to the image locally; and if developers don't want to build it, they can …
> Install + configure Celery

- django/src/rdwatch/urls.py
- django/src/rdwatch/utils/satellite_bands.py
- django/src/rdwatch/utils/worldview_processed/satellite_captures.py
- django/src/rdwatch/utils/worldview_processed/stac_search.py
- django/src/rdwatch/views/__init__.py
- django/src/rdwatch/views/region.py
- django/src/rdwatch/views/tile.py
- docker-compose.yaml
- vue/src/client/services/ApiService.ts
- vue/src/components/MapLibre.vue
- vue/src/components/ModelRunList.vue
- vue/src/components/SettingsPanel.vue
- vue/src/components/SideBar.vue
- vue/src/interactions/satelliteLoading.ts
- vue/src/interactions/timeStepper.ts
- vue/src/mapstyle/index.ts
- vue/src/mapstyle/rdwatchtiles.ts
- vue/src/mapstyle/satellite-image.ts
- vue/src/store.ts
Refactors the request for satellite timestamps to do both sentinel and world-view at the same time.
- Instead of returning a flat list of timestamps it returns a list of objects (sorted by timestamp) which indicate each timestamp's source, collection, cloudcover).
- The front end has been modified to use this new data structure for the timestamps.
- There is a cloud cover filter and checkboxes to filter between S3 and WorldView Imagery.
Tips:
- US0005 is a decent sample region to look at to see the images.
Issues:
- Worldview Imagery takes a **LONG** time to download from the server if the region is decently large.  You can watch the console output and see the range requests happening.  I don't know enough about the COGReader and if there is a better way to do this.  I feel like it is …
> Refactor Satellite timeStamp requests

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
This will speed up reporting of linting errors by caching the install of the pre-commit hooks.
> Add caching to CI linting job

- Dockerfile
Will enable us to run management commands inside the production container more conveniently.
> Include `manage.py` in Django image

- django/src/rdwatch/utils/worldview_processed/satellite_captures.py
To reproduce this bug, go to the following URL in any RGD deployment:
`/api/satellite-image/visual-timestamps?start_timestamp=2014-01-01T00:00:00&end_timestamp=2022-12-01T00:00:00&bbox=25.5370616,-33.791286441000004,25.5477044,-33.785965041000004`
It seems there are some worldview STAC assets that don't contain the expected `B01` field. I don't know what that field is, or why it would or would not be present in a STAC asset, but to my untrained eye it looks like the particular entry that is missing the  `B01` field is some sort of image _metadata_ and not an actual image. While most (maybe all?) of the other assets returned from the STAC server for WorldView appear to be TIFs, this particular asset is a IMD file, with the description `"IMD Metadata carried over from source data"`. …
> Fix KeyError in WV imagery function

- django/src/rdwatch/server/settings.py
- template.env
This decouples it from the DEBUG env var, and allows the DEBUG var to be set while also enabling redis cluster mode.
This will require a corresponding change in the rgd_aws_infrastructure repo.
> Control redis cluster mode with its own env var

- django/src/rdwatch/server/settings.py
We're using IAM roles for authentication, not access keys, so these env vars aren't needed.
> Remove unneeded env vars from django settings

- django/src/rdwatch/server/settings.py
Our NGINX config allows up to 128 MB for JSON POST bodies, but Django has a default limit of 2.5 MB.
> Make Django max upload size consistent with NGINX config

- django/src/rdwatch/tasks/__init__.py
- django/src/rdwatch/urls.py
- vue/src/client/services/ApiService.ts
- vue/src/interactions/mouseEvents.ts
Based on the comments on the previous PR I've refactored and improved a couple things.
- Only one function `get_range_captures` where closest capture just specifies a timebuffer of 1 day and then filters for the closest capture
- The Temporary File writing is eliminated, I could write the bytes directly into a Django File object instead of requiring any temporary file.
- changed from `get-images` to `generate-images` in frontend/backend
- Cleaned up some dangling stuff for area calculations in the client.
> Refactor Site Observation Image Fetching

- docker/docker-entrypoint.sh
Cherry picked out of #192 , these are more urgent fixes than the rest of that PR.
- Runs `poetry install` before migrations. In some situations, the migrations are run _before_ any `poetry install` command happens, which causes an error if there are missing dependencies.
- Ignore failed `migrate` command. This might happen if `django-admin` is not installed in the docker image yet.
- Add lookups fixture loading to docker image. This should be fine, as the operation is idempotent due to the primary keys of each row being specified in the fixture.
> Fix migrations not running on deploys

- django/src/rdwatch/models/site_evaluation.py
- django/src/rdwatch/models/site_observation.py
- django/src/rdwatch/schemas/region_model.py
- django/src/rdwatch/schemas/site_model.py
- django/src/rdwatch/tests/test_ingest.py
#191 fixed this for site evaluations, but not site observations; this PR fixes that.
> Support missing `score` for site observation

- django/src/rdwatch/models/site_observation.py
- django/src/rdwatch/schemas/region_model.py
- django/src/rdwatch/schemas/site_model.py
The spec for site models has been updated, this PR tweaks our ingest routines to account for these changes. Most notably, site `observations` can now have either `Polygon` or `MultiPolygon` geometries.
> Update site model ingest routine to latest spec

- docker/docker-entrypoint.sh
This is already done in the Dockerfile and shouldn't need to be repeated. It also seems to be causing a deployment failure when I tried deploying the latest image, logs are here https://us-west-2.console.aws.amazon.com/ecs/v2/clusters/resonantgeodatablue-fargate-cluster/services/resonantgeodatablue-worker-service/tasks/762716d1bb7a43e7a3fdd18d5b23f873/logs?region=us-west-2
> Don't run poetry install in docker entrypoint

- Dockerfile
Since we relocated the venv directory to `/poetry/venvs` instead of `/app/django`, we now need to explicitly copy it in the final build stage. Deploys are currently failing with an error due to this issue.
> Explicitly copy venv dir in docker build

- docker/nginx.json
Follow up to #212, this was also causing deployment failures.
> Update nginx-unit venv path

- DEVELOPMENT.md
- django/src/rdwatch/server/settings.py
- django/src/rdwatch/tasks/__init__.py
- django/src/rdwatch/utils/images.py
- docker-compose.override.yaml
This PR 
- Moves all non-task functions out of `rdwatch.tasks` and into their own module
- This is the usual practice when it comes to celery tasks AFAIK, and it also makes it easier to see all celery tasks at a glance. @BryonLewis any objections to this?
- Adds a new docker compose service for celery beat and instructions for running it natively.
- Adds a stub task that runs once a minute. I will make a follow up to actually implement the "temporary" model run logic, where this task will be responsible for querying for and deleting model runs that need to be deleted.
> Add celery beat

- Dockerfile
- docker/nginx.json
Sets the `path` attribute for nginx unit - see https://unit.nginx.org/howto/django/#interface-wsgi
> Add root path of Django app to `nginx.json`

- Dockerfile
This env var needs to be set before the `docker-entrypoint.sh` script is run, since that script runs `poetry` commands.
> Set `VIRTUAL_ENV` env var before docker entrypoint

- django/src/rdwatch/migrations/0009_hyperparameters_created_and_more.py
- django/src/rdwatch/models/hyper_parameters.py
- django/src/rdwatch/serializers/hyper_parameters.py
- django/src/rdwatch/tasks/__init__.py
- django/src/rdwatch/tests/test_model_runs.py
- django/src/rdwatch/views/model_run.py
- django/tox.ini
This PR adds `created` and `expiration_time` fields to the HyperParameters model. The `expiration_time` is set by the user at model run creation time, and is measured in hours. An hourly celery beat task checks for any "expired" model runs and deletes them + all of their evaluations and observations.
> Auto-deletion of model runs

- django/src/rdwatch/api.py
- django/src/rdwatch/urls.py
- django/src/rdwatch/views/__init__.py
- django/src/rdwatch/views/satellite_image.py
- django/src/rdwatch/views/vector_tile.py
Doing this first before integrating caching, since presumably we'll want to use ninja's native caching mechanism.
> Convert vector tile endpoint to ninja

- django/src/rdwatch/urls.py
This is a temporary feature that will help consumers of the API to migrate to the new trailing slash endpoints.
> Add temporary backwards-compatible endpoints

- django/src/rdwatch/api.py
- django/src/rdwatch/views/vector_tile.py
- vue/src/client/models/ModelRun.ts
- vue/src/components/MapLibre.vue
- vue/src/components/ModelRunList.vue
- vue/src/interactions/mouseEvents.ts
- vue/src/mapstyle/index.ts
- vue/src/mapstyle/rdwatchtiles.ts
- vue/src/store.ts
Backend changes:
- Move the vector tiles endpoint underneath the `model-runs` prefix (i.e. the endpoint is now `/api/model-runs/<id>/vector-tile/z/x/y.pbf`) and require a model run ID to filter by. The vector tiles are then generated based on the evaluation/observation/region polygons associated with that model run, as opposed to every polygon in the database that intersects with the given coordinates.
Frontend changes:
- Move model runs / opened model runs into the global state
- Refactor the `rdwatchtiles` to create a new vector tiles layer for every selected model run. This means that vector tiles will only be fetched for the currently selected model runs.
> Limit vector tiles by select model runs

- DEVELOPMENT.md
- django/src/rdwatch/admin.py
- django/src/rdwatch/models/hyper_parameters.py
- django/src/rdwatch/server/settings.py
- django/src/rdwatch/server/urls.py
Adds the needed settings in order to enable the Django admin at `/admin`. I sometimes find this easier to use then `shell_plus` or looking at the database itself.
Settings needed to enable this were taken from
https://github.com/girder/django-composed-configuration
> Enable Django admin

- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/server/settings.py
The `CacheURLValue` class from `django-configurations` doesn't allow specifying a key_prefix, which was causing auth errors between the Django app server and Redis for some reason. This PR updates that setting to explicitly specify the `CACHES` dict instead. It also removes the `cache` extra from the `django-configurations` dependency as we no longer need it now.
> Fix failing deploy due to `CACHES` change

- .github/workflows/cd.yaml
@mvandenburgh  Mind merging this? The GH action now lives at [girder/create-pip-index-action](https://github.com/girder/create-pip-index-action).
> Update GH action location

- django/src/rdwatch/views/model_run.py
- scripts/loadModelRun.py
- vue/src/client/services/ApiService.ts
I made a sample set by reloading the Dubai region multiple times to get a sense of where the performance issues were. 
I had a hunch that it was searching into each observation.  I had removed most observation searches by moving the date/time range up into the Evaluation area.
I decided to remove the bbox case of looking at observation geometries and focus more on the evaluation geometry.  I also could remove the observation count by removing this.  Now a model run doesn't have to look into each site observation (of which there could be hundreds per site evaluation) to calculate geometry, it will grab it from the higher level.
There could be an argument for the future that the model-run list doesn't need geometry at all and it could be removed in the future so that when a user clicks on a …
> Remove observation searching for geometry  in model-run endpoint

- django/src/rdwatch/views/model_run.py
- vue/src/client/services/ApiService.ts
- vue/src/components/ImagesDownloadDialog.vue
- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
- vue/src/components/annotationViewer/SideBar.vue
- vue/src/components/filters/PerformerFilter.vue
- vue/src/store.ts
Per the goals document for the MVP one of the items listed was enabling multiple performers to be selected.
This PR updates the back-end and front-end to allow for multiple selections of performers.  Mostly just changes the 'performer' filter field to an a list of performers instead of a single performer.
The front-end right now increases the height of the box to fit more performers, we may want to revisit this behavior.
> Update performer filter to allow multi-select

- .pre-commit-config.yaml
- scripts/loadGroundTruth.py
- scripts/loadModelRun.py
I made some improvements to the upload scripts to make things faster, namely, using the `multiprocessing` model to do uploads in parallel. A new CLI argument, `--parallelism`, allows the user to specify the number of concurrent uploads to do at once. It defaults to the value returned by `os.cpu_count()`. This significantly speeds up upload when you're trying to get a large number of model runs loaded into your system quickly.
I also added the `scripts/` subdirectory to the pre-commit config.
> Parallelize model run upload scripts

- scripts/loadGroundTruth.py
- scripts/loadModelRun.py
The auth cookie is now called `token` in the new auth infrastructure.
> Update cookie value for AWS deployment

- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/server/settings.py
- django/src/rdwatch/server/urls.py
Installs [`django-debug-toolbar`](https://github.com/jazzband/django-debug-toolbar) as a dev dependency and enables it in `DevelopmentConfiguration`. In particular, this will make it more convenient to profile SQL queries.
> Add `django-debug-toolbar` as a dev dependency

- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/utils/satellite_bands.py
- django/src/rdwatch/utils/stac_search.py
- django/src/rdwatch/utils/worldview/satellite_captures.py
- django/src/rdwatch/utils/worldview/stac_search.py
- django/src/rdwatch/utils/worldview_processed/satellite_captures.py
- django/src/rdwatch/utils/worldview_processed/stac_search.py
This PR installs `pystac-client` and uses it to query the STAC API instead of manually crafting HTTP requests. The next step is to remove the code that parses the raw JSON blob from the STAC server, and instead use the pystac-client's built in parsing functionality; I'll include that in a follow up PR. 
One additional thing to note is that the pystac client handles pagination
automatically. So, I've removed the manual pagination handling code as well.
> Use `pystac-client` to make STAC requests

- django/src/rdwatch/admin.py
- django/src/rdwatch/fixtures/lookups.json
- django/src/rdwatch/migrations/0014_remove_region_uniq_region_and_more.py
- django/src/rdwatch/models/lookups.py
- django/src/rdwatch/models/region.py
- django/src/rdwatch/utils/tools.py
- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/region.py
- django/src/rdwatch/views/site_evaluation.py
Currently in the RGD database, we break region strings up into multiple columns (i.e. for `AE_R001`, we store the country (AE), type (R), and id (0001) in separate columns). The T&E database on the other hand simply stores the region as a single string. This PR brings the RGD db in line with the T&E db.
This is a prerequisite for embedding region names directly in the vector tile metadata (at least, it makes it significantly simpler); I'll make a follow up PR that implements that change.
> Denormalize region name into a single column

- django/src/rdwatch/views/model_run.py
When looking at proposals the front-end was swapped to a direct string name but the back end was still providing an object 
`{ id: int; name: string}`.  This resulted in the name under proposals being `[Object object]_9999` instead of compounding the region name with the siteId (non-DB Id but the real Id).  Just updated the `get_region` function in model_run.py to fix the issue.
> Fix proposal region name

- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/region.py
- django/src/rdwatch/views/vector_tile.py
- django/src/rdwatch_scoring/views.py
- vue/src/client/models/Region.ts
- vue/src/client/services/ApiService.ts
- vue/src/components/MapLibre.vue
- vue/src/components/ModelRunDetail.vue
- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
- vue/src/components/annotationViewer/ModelRunSiteEvalList.vue
- vue/src/components/annotationViewer/SideBar.vue
- vue/src/components/filters/RegionFilter.vue
- vue/src/components/siteObservations/EvaluationDisplay.vue
- vue/src/components/siteObservations/EvaluationScoring.vue
- vue/src/interactions/mouseEvents.ts
- vue/src/mapstyle/annotationStyles.ts
- vue/src/mapstyle/rdwatchtiles.ts
- vue/src/store.ts
- vue/src/views/AnnotationViewer.vue
- vue/src/views/RGD.vue
This PR removes any notion of region "IDs" from the external-facing API. Regions are now referenced entirely by their string, just as in the T&E database.
> Refactor backend + frontend to reference `Regions` by string name instead of numerical ID

- django/src/rdwatch/views/site_image.py
- django/src/rdwatch/views/site_observation.py
Just noticed two locations where the siteobs_id was still an int which would cause nasty ninja validation errors when downloading images or viewing them.
There is a secondary problem that I can't figure out at all.  If you bring up a model run and click on a polygon it displays in the right side of the screen.  If you hover over that card on the right side of the screen it's supposed to highlight the polygon by making it thicker.  This is to associate your card with a polygon.  For some reason this makes all annotations disappear at once when you hover over the card.  I tried looking into the filters and a bunch of areas but this has me stumped.
> Fixes the site image endpoints by changing the int to str

- DEVELOPMENT.md
- docker/docker-entrypoint.sh
Running these on **every** container start is causing issues on our ECS deployment on AWS. Specifically, the problem is that the migrations in #272 take several minutes to run; on top of that, each container (the django web app, celery worker, and celery beat) each tries to run the migration command at once. This results in one of them acquiring a lock and beginning the migrations, while the other two sit there waiting. While not ideal, this wasn't an issue for short-running migrations up to this point. But now that we have a minutes-long migration, it looks like some Django mechanism that detects deadlocks kicks in for the other two containers and causes the container to exit with a non-zero status code. This in turn signals to CloudFormation that the deploy failed, which causes it to …
> Remove migrations/fixture loading from docker entrypoint

- django/src/rdwatch/tasks/__init__.py
- django/src/rdwatch/utils/images.py
- django/src/rdwatch/utils/worldview/raster_tile.py
- django/src/rdwatch/utils/worldview_processed/raster_tile.py
- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/site_observation.py
- vue/src/client/services/ApiService.ts
- vue/src/components/ImagesDownloadDialog.vue
- vue/src/components/imageViewer/ImageViewer.vue
- I had to previously change some `rgb.data =` to `rgb.from_array(` but I missed assignment before.  I updated that so the pan-sharpening images should now download properly.
- While I was in here I added a download option to use the bits per pixel to scale the image instead of the default value of 10,000.  This will brighten up a lot of the dark images.
- I then added the corresponding UI to the front-end when selecting WV images to show that option for changing the scaling method from 'default' to 'bits'.
> pan sharpening fix

- scripts/loadModelRun.py
Regions are now returned from the API as simple strings, not objects. I missed this in #268, and noticed this when uploading proposals to test #278.
> Update model run upload script for new endpoint response format

- django/src/rdwatch/tasks/__init__.py
Happened to miss the option to add the pansharpening to non-observation images.  This adds it back in.
> Add pansharpening to non-observations

- django/src/rdwatch/api.py
- django/src/rdwatch/models/site_evaluation.py
- django/src/rdwatch/models/site_observation.py
- django/src/rdwatch/schemas/region_model.py
- django/src/rdwatch/schemas/site_model.py
The autogenerated swagger page provided by ninja wasn't working due to the use of complex types like `GEOSGeometry` and `Polygon` directly in our pydantic request models. I moved those to dynamic properties and updated the ingest code to use those, and it works now. See `/api/docs/`.
> Fix ninja swagger page not working

- django/src/rdwatch/schemas/site_model.py
The site model schema only specifies `cache` as a generic object, so we can't assume that these fields exist just because `cache` exists.
I don't think this will impact the fields on the `SiteEvaluation` model, since they are already nullable in the case that there is no `cache` at all.
> Allow `cache` values to be null in site model schema

- vue/package-lock.json
- vue/package.json
- vue/src/components/imageViewer/ImageViewer.vue
- vue/src/components/imageViewer/ImageViewerButton.vue
- vue/src/components/imageViewer/imageUtils.ts
- vue/src/components/siteObservations/EvaluationDisplay.vue
- vue/src/mapstyle/annotationStyles.ts
- vue/src/store.ts
- Adds a tool called 'canvas-capture' which is based on 'ccapture.js' for creating GIFs in the client and downloading them from a canvas.  That's why there are package.json and package-lock.json changes.
- On hitting the download button a secondary hidden canvas is created and draws the images uses requestAnimationFrame, the canvas-capture tool then records the information and generates a GIF once complete.
- The drawing tool for the images has been modified to accept an override Width/Height which can resize to a specific value.  This is used to find the max size of the images in the `filteredImages` list and then rescale everything to the same size.  If all images are below 500px in any dimension it will resize them so that the smallest dimension is 500px.
- Added a section to the draw …
> Downloading Image Sequences

- django/src/rdwatch/tests/test_model_runs.py
- django/src/rdwatch/views/model_run.py
- scripts/loadModelRun.py
- vue/src/client/models/ModelRunList.ts
- vue/src/components/ModelRunList.vue
This PR switches the model run endpoint to use ninja's built-in pagination instead of a manual approach; this involved refactoring the query to remove the JSONB aggregation, which improves readability regardless. Note I haven't removed any fields yet, and the structure of the response returned by the model run LIST and GET endpoints remains mostly unchanged. The exception to this is that `results` becomes `items` in the list endpoint response; this was done to bring the endpoint in line with ninja's default pagination behavior. But in general, this PR is just a refactor that will make it easier to do more extensive changes to the endpoint in a followup PR. 
However, removing the large JSONB aggregation does seems to improve performance on its own, bringing the response time down from …
> Switch to ninja's built-in pagination for model runs endpoint/eliminate JSONB subquery

- django/src/rdwatch/views/site_evaluation.py
- vue/src/client/services/ApiService.ts
Calling `.dict()` on a pydantic model instance with `exclude_unset` set will cause values that are not present/undefined to simply be excluded from the resulting dict instead of casting them to `None`, while values that are explicitly set to `null` in the request body will be cast to `None` as expected. 
[Docs for `exclude_unset`](https://docs.pydantic.dev/1.10/usage/exporting_models/#modeldict)
> Ignore unset values in PATCH request body

- django/src/rdwatch/views/site_evaluation.py
- vue/src/client/services/ApiService.ts
- vue/src/components/imageViewer/ImageViewer.vue
`null` and the date have specific meanings in RGD.
When we do an approve/reject or the reverse we make a call to the patch endpoint with the other fields empty.
Python/django-ninja don't make a distinction between and empty parameter in the body or a null one.  So a call to the approve/unapprove/rejected endpoint would set the start/end dates to null/None.
I tried seeing if I could interpret and see if the keys are available in the dictionary of the request but by default it sets them to None.
I tried looking up some stuff to see if Ninja had a good way to differentiate between Null/None and an empty parameter but I couldn't find anything.
So in the client side I injected a string 'null' for the value if the request if it is explicitly set and the back-end will read this and set the date …
> Fix Proposal Patch

- django/src/rdwatch/views/model_run.py
The type annotation for `expiration_time` is incorrect. Note that if no model runs in the DB have an `expiration_time` set, this bug will not occur. However, if there is at least one model run with a non-null `expiration_time` in the database, all calls to the `/api/model-runs/` endpoint will fail. I assume this went unnoticed because it's not common to set an `expiration_time` for model runs in local development, so we didn't notice until today when I deployed it and saw API calls start failing.
> Fix type error in model run response schema

- scripts/loadModelRun.py
This logs out the response body if an ingest error occurs. Currently, it just reports a `422` error.
T&E was seeing some 422 errors coming back from RGD due to a validation error with the site models they were uploading using this script, but it wasn't clear what the problem was because nothing was being logged.
> Log response body if model run ingest fails

- scripts/loadGroundTruth.py
The `model_runs` dict wasn't being reset after site-models are finished uploading, causing all site-models to be reuploaded as region-models.
> Fix bug in ground truth upload script

- .gitignore
- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/site_evaluation.py
I forgot to check the downloading of group annotations in our conversion to the UUID format.
This resulted in not being able to download groups of proposals.  I'd have to look more into why the type system didn't yell about this before and started yelling recently.
- Updated the relevant model-run endpoint to use str.  I don't know why I had it using int before, the task-id is stored as a charfield.
- Update the function for exporting annotations to use UUID4
- I added the celerybeat and noup.out to the .gitignore.  Was sick of having to skip those files when adding all my commit files.
> fixing annotation group export

- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/site_evaluation.py
- vue/src/client/services/ApiService.ts
- vue/src/components/ImagesDownloadDialog.vue
- vue/src/components/ModelRunList.vue
- Fixes the customDate override downloading.  I was using a different parameter name for some reason on the client side.  I must have changed it at sometime because it was working before.
- Fixes ordering by removing the client side ordering and ordering in Django, by making newer non-GT model runs first followed by the GT model runs.
- Modified the export to zfill 4 places instead of 3.  I kept getting 003 and 002 when exporting.  I wanted to fix this issue.
> fix override date error, ordering, padding for regions

- .github/workflows/cd.yaml
The ARM image is unused, and takes significantly longer to build than the x86-64 image.
> Stop building ARM variants of RD-WATCH docker image

- .github/workflows/cd.yaml
Apparently, this is needed to build the image. 
Partially reverts #298
> Add back `docker buildx` install to CD workflow

- django/src/rdwatch/tasks/__init__.py
- Fixed max_bbox/max_time confusion in calculating the time
- Added Scale setting to S2/L8 Non-Obs image downloading
- Changed the count number for images to a generated uuid to hopefully prevent future conflicts.
> Satellite Task fetching fixes

- vue/package-lock.json
- vue/package.json
- vue/src/components/imageViewer/ImageViewer.vue
Vuetify released an updated version with some changes to the Vue-Date-Picker: [v3.3.4](https://vuetifyjs.com/en/getting-started/release-notes/?version=v3.3.4
)
Some of the usage before has changed.
- I believe that before the model-value/v-model updated when the date was changed.  This one the value only updates when the user clicks 'OK'.
- I don't know if I really like this behavior but I needed to adjust the current component to fix it.
- I also added the ability for it to load the proper current date when initially clicking the edit button.
> fixing date/time picker and updating vuetify

- django/src/rdwatch_scoring/views/vector_tile.py
Add iMERIT as a valid originator for a ground truth label, as requested by T&E team.
> Adding iMERIT as a valid originator for ground truth

- django/src/rdwatch/views/vector_tile.py
- django/src/rdwatch_scoring/views/vector_tile.py
- vue/src/client/services/ApiService.ts
- vue/src/components/LayerSelection.vue
- vue/src/components/MapLegend.vue
- vue/src/components/ModelRunDetail.vue
- vue/src/components/ModelRunList.vue
- vue/src/components/PopUpComponent.vue
- vue/src/components/SideBar.vue
- vue/src/components/annotationViewer/SideBar.vue
- vue/src/components/filters/PerformerFilter.vue
- vue/src/interactions/mouseEvents.ts
- vue/src/interactions/popUpType.ts
- vue/src/main.ts
- vue/src/mapstyle/annotationStyles.ts
- vue/src/mapstyle/rdwatchtiles.ts
- vue/src/store.ts
- vue/src/views/AnnotationViewer.vue
- vue/src/views/RGD.vue
Notes:
- Added a `Case(` to the scoring vector_tile endpoint for the color_code parameter.  It needs to check two different tables based on if it is ground truth or not.
- Modified Vector Tile to also return more data for the `sites` so a popup can be used properly.  This included stuff like configuraiton_name, and performer_name
- I removed a lot of the older ScoreColoring logic from the front-end because it is no longer needed.
- Refactored the `drawObservations` and `drawSitePolygons` to be undefined or an array consisting of 'model or 'groundtruth'.  This allows for different combinations of the 4 states to be drawn at once.
- LayerSelection.vue component is used to manage the layers being shown.
- I added the performerMap to the store because I needed a reference to the performer …
> Scoring Coloring from T&E Database

- vue/src/components/ImagesDownloadDialog.vue
Fix the date picker closing the menu if anything except a day on the calendar was clicked
> Fix date picker on download image prompt

- vue/src/App.vue
- vue/src/components/ErrorPopup.vue
This configures the Vue app with a global error handler that will catch any JavaScript errors that are thrown and render them in a UI popup. A copy-to-clipboard button is included to make including these errors in bug reports easier.
Here's an example of a background request failing:
https://github.com/ResonantGeoData/RD-WATCH/assets/37340715/d94be735-5dca-4ac4-a9cf-d4f01e7d5631
And here's an example of an error with a longer stack trace to demonstrate the scrolling functionality (i inserted a `throw Error('...')` manually here)
https://github.com/ResonantGeoData/RD-WATCH/assets/37340715/2dd6ef66-2c57-43ed-8132-46c198df8ca4
> Add global error handler/popup snackbar

- vue/src/components/ImagesDownloadDialog.vue
- vue/src/components/ModelRunDetail.vue
This prevents unnecessary API requests from being fired if the user clicks a button multiple times.
> Add debouncing to some buttons

- vue/src/App.vue
- vue/src/components/ErrorPopup.vue
- vue/src/components/SideBar.vue
- vue/src/store.ts
Moves the error popup into a dialog that the user must open themselves. When an error occurs, the button in the top right corner will become clickable. If the user clicks it, a popup dialog will appear with the error text. 
Demo:
> Redesign error popup UI

- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/tasks/__init__.py
I noticed model runs with an expiration time on them weren't being deleted as expected. Looking at the AWS container logs, something is causing a OOMKilled error to occur. I didn't know this was a thing, but apparently calling `.delete()` on a QuerySet will (most of the time at least) cause Django to load each object into memory. I expected it to just do a `DELETE` query, but I guess Django has to do some extra housekeeping with signals and cascades (see [here](https://stackoverflow.com/questions/31477723/how-to-prevent-django-from-loading-objects-in-memory-when-using-delete) for more info).
This PR refactors that task to do deletions in batches, to avoid loading every model run/site evalutation/site observation that's being deleted into memory at once.
> Fix memory usage in delete task

- django/src/rdwatch/views/model_run.py
We weren't including the `page` parameter in the cache key, so the server was returning the same results for every `page` in a model run.
> Fix model run cache bug

- vue/src/components/ModelRunDetail.vue
Moves the `mode` of a model run to the corner of its card and includes a visual icon to indicate whether its "batch" or "incremental". If a model run doesn't have a `mode` or its `mode` is `null`, nothing is displayed (as is the case for non-scoring model runs)
I'm open to suggestions on icons to use.
> Redesign model run mode display

- django/src/rdwatch_scoring/views/model_run.py
- vue/src/client/services/ApiService.ts
- vue/src/components/LayerSelection.vue
- vue/src/components/ModelRunDetail.vue
- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
- vue/src/components/filters/ModeFilter.vue
- vue/src/components/imageViewer/ImageViewerButton.vue
- vue/src/mapstyle/rdwatchtiles.ts
- vue/src/store.ts
Adds a new filter for evaluation run modes.
Depends on #336 being merged first.
> Add mode filter

- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/region.py
- django/src/rdwatch_scoring/api.py
- django/src/rdwatch_scoring/views/__init__.py
- django/src/rdwatch_scoring/views/eval.py
- django/src/rdwatch_scoring/views/model_run.py
- django/src/rdwatch_scoring/views/region.py
- vue/src/client/index.ts
- vue/src/client/models/Eval.ts
- vue/src/client/models/EvalList.ts
- vue/src/client/services/ApiService.ts
- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
- vue/src/components/filters/EvalFilter.vue
- vue/src/components/filters/PerformerFilter.vue
- vue/src/components/filters/RegionFilter.vue
Taking #338 and made some changes for the UI and fixing some Warnings/errors
- No Eval for RGD endpoint error
- fixes Performer warnings for recursive lookups
- ran pre-commit and linting
- Added page sizes for region endpoints of 1000 (when loading all annotations in RGD you get more than 100 regions).
Changed some vuetify logic to make the filters look like this:
> 1.3 eval filter

- django/src/rdwatch/tasks/__init__.py
- django/src/rdwatch_scoring/tasks/__init__.py
- vue/src/components/SideBar.vue
This fixes a bug in the time range downloading of satellite images.
Background:
- The timerange feature for downloading images would usually take the Site Start/End date and add 30 days to each end to grab more information.
- Our internal functions rely on a timestamp + time buffer to determine what to request from the STAC server.  So after adding the 30 days to max and substracting the 30 days from the min we could get a date range and divide that by 2 to get a time buffer.
- This time buffer was then added to the min_time - 30 days to get a central date in the range.  That central date was given to the function with time buffer.
Bug:
The bug happened in calculating the central timestamp.  Instead of `min_time - 30 days` it was `min_time + 30 days` this would set the whole time range …
> TimeRange Downloading Bug

- vue/src/client/models/ModelRun.ts
- vue/src/client/services/ApiService.ts
- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
- vue/src/components/annotationViewer/SideBar.vue
- vue/src/components/filters/EvalFilter.vue
- vue/src/components/filters/PerformerFilter.vue
- vue/src/components/filters/RegionFilter.vue
- vue/src/store.ts
- Swapped instances of `watchEffect` to `watch` to be more explicit about what values are triggering a request to gather more data.  I.E the filters only change when the value changes, this could be changed by the ApiPrefix switching from the standard `/` to `/scoring` or if the value changes outside of the component.  This happens in Regions due to the URL route for different regions.
- This resulted in removing some redundant calls to update values.
- I removed the `nextPage` emit signal loop from `ModelRunList.vue` up to `SideBar.vue`.  Now it's managed by the `ModelRunList.vue` instead of making that round trip.
- Removed references to `hasScores` it was the old way to connect data between the scoringDB and the RGD DB.  It's no longer needed so I removed some code that was there.
> Client Filter Refactors

- DEVELOPMENT.md
- docker-compose.override.yaml
- vue/vite.config.ts
- Adds a rdwatch-client service to the docker-compose.override.yml
- I need to mount the full app because we need the git information for the client to display the hash.
- I copy over the folder (mounted as read only) so npm can install node_modules without messing with the user's local permissions
- There is a git config setting to allow it to read data that isn't owned by the user for the client hash displaying
- NPM install is ran and then npm run dev to launch the server
- vite config is modified with an environment variable `VITE_DOCKER_DEVELOPMENT` which tells it to proxy to the `django` container instead of `localhost`.
- If the `VITE_DOCKER_DEVELOPMENT` is false it will instead run the dev server at `localhost:3000` so it isn't conflicting with the docker compose service port.
I'm …
> Docker Client Dev Service

- vue/src/components/imageViewer/ImageViewer.vue
- vue/src/components/imageViewer/imageUtils.ts
When using the rescaling function on the image-viewer there were complaints that it was difficult to see the S2/L8 images because they were scaled up to match the geospatial bounds of the WV images.
This PR adds an option in the settings to zoom out the rescaled images to provide more context for the S2/L8 images (up to 5X the size of the box).
Since we don't have any additional data for the WorldView image outside of it's bounds it is marked as gray outside of the area.
Note: 
- Zooming out on a mix of WV and S2 can result in a large GIF because I'm still displaying the WV at native resolution.  I.E if the WorldView resolution is 500x500 and you zoom out 2X then all images in the GIF sequence are now 1000x1000 with the S2/L8 images upscaled to fit there.
> Image Viewer Rescaling 

- vue/src/components/imageViewer/ImageViewer.vue
Per an issue in gitlab about notes overflowing and not having enough room to type notes.
- switched to truncate: ellipsis for the notes with a tooltip hover to show the full note
- The v-text-field was change to a v-textarea to allow easier editing.
> Notes Update

- django/src/rdwatch/schemas/site_observation.py
- django/src/rdwatch/tasks/__init__.py
- django/src/rdwatch/utils/satellite_bands.py
- django/src/rdwatch/utils/stac_search.py
- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/site_observation.py
- django/src/rdwatch_scoring/tasks/__init__.py
- django/src/rdwatch_scoring/views/observation.py
- vue/src/client/services/ApiService.ts
- vue/src/components/ImagesDownloadDialog.vue
- vue/src/components/annotationViewer/ProposalList.vue
- vue/src/components/imageViewer/ImageViewer.vue
- vue/src/components/imageViewer/imageUtils.ts
- vue/src/components/siteObservations/EvaluationDisplay.vue
- vue/src/components/siteObservations/EvaluationImages.vue
- vue/src/components/siteObservations/EvaluationsSideBar.vue
- vue/src/store.ts
This PR adds support for PlanetLab (PL) imagery. I just used the equivalent Accenture collection (`ta1-pd-acc-3`) to the ones we use for L8 and S2. The UI has been updated to display info/accept PL as an input for downloading images, and all the necessary backend code has been updated to support PL images.
This PR probably seems more complicated than it actually is at first glance; essentially all the changes are just adding an additional `PL` option to every place in the codebase where sensor types are enumerated. The existing L8/S2 code seems to work perfectly for PL as well.
> Add support for PlanetLab imagery

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- Dockerfile
- django/poetry.lock
- django/pyproject.toml
- django/src/rdwatch/server/settings.py
- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/site_evaluation.py
- django/src/rdwatch/views/site_image.py
- django/src/rdwatch/views/site_observation.py
- django/src/rdwatch_scoring/views/observation.py
- django/src/rdwatch_scoring/views/site_image.py
I skimmed this page https://docs.djangoproject.com/en/5.0/releases/5.0/#backwards-incompatible-changes-in-5-0, and the only breaking changes I found were https://github.com/ResonantGeoData/RD-WATCH/pull/368/commits/7062c4991142d8ebec92d89176b6a7f00414bc93 and https://github.com/ResonantGeoData/RD-WATCH/pull/368/commits/ee555d9dfa352054a11039e5a8ce8118361e5d1b.
> Dependency updates

- vue/src/components/SideBar.vue
This was a minor thing that resets the satellite icon when a user changes the selectedRegion.  I had it but forgot to commit it in my latest version of the guard the other dayt.
> minor satellite timestamp fix

- django/src/rdwatch/views/model_run.py
- django/src/rdwatch/views/site.py
- django/src/rdwatch/views/site_evaluation.py
- django/src/rdwatch_scoring/views/site.py
- vue/src/client/services/ApiService.ts
This changes every endpoint to end with a backslash, as well as the corresponding client code. This will avoid unnecessary redirect requests in the frontend.
> Make endpoint backslashes consistent

- Dockerfile
- django/src/rdwatch/api.py
- django/src/rdwatch/server/settings.py
- django/src/rdwatch/views/server_status.py
- docker-compose.override.yaml
It was starting to become difficult to keep track of what's deployed on the different deployments we have. Now that we're referring to each release by it's version number, I think it's much better to use that for versioning instead of the full commit hash.
I didn't put this in the UI yet, but maybe we should rework that at some point to hit the `/api/status` endpoint instead of statically bundling that info in the JS code. Maybe something to think about in the future when we have more time.
> Include current version in server status endpoint, swagger page

- .github/workflows/cd.yaml
After merging #381, the github actions runner was still running out of space. This PR is a stopgap to allow us to at least publish images until we can sort out what is taking up so much space on the runner.
cc @BryonLewis ^ just so you're aware. I'll merge this now so we can get the tagged release image to build tomorrow after #384 is merged, but we should maybe discuss what to do about this going forward.
> Free up space on GH actions runner before build

- tileserver/devServer.mjs
- tileserver/package-lock.json
- tileserver/package.json
- tileserver/rgd.mjs
- tileserver/scoring.mjs
- vue/src/mapstyle/index.ts
- vue/src/mapstyle/rdwatchtiles.ts
Adds a year filter to the vector tiles endpoint. This makes it so that the client must supply a year representing the range of site observations they wish to view. The client makes additional requests if the user slides the time slider to a new year.
This resolves the performance issues for large sites that contain a significant amount of observation polygons.
> Add year filter to vector tiles endpoint

- vue/src/components/imageViewer/ImageViewer.vue
Async issue when getting information for another selected site it wasn't waiting to display the information for it.  So it was lagging behind and selection was offset.
https://github.com/ResonantGeoData/RD-WATCH/blob/4d6fa70a83e389a79943002f6f28806729b8fac2/vue/src/components/imageViewer/ImageViewer.vue#L129
This is where it loads in the new images to display so really the image-editor shouldn't be displayed unless there is data in the `combinedImages` indicated by it having a length > 0;
> proposal image fix

- vue/src/components/annotationViewer/ProposalList.vue
- vue/src/components/imageViewer/ImageEditorDetails.vue
- Fixes issue annotators were noticing with setting notes to a blank or '' empty string.
- Also fixes issue with Date not properly displaying after hitting 'save'.  It was loading the previous DateRange instead of calculating a new one for the currently selected proposal.
> Proposal Saving

- django/src/rdwatch/views/model_run.py
- django/src/rdwatch_scoring/views/model_run.py
Small updates to enable selecting scoring properly with the new region relationship.
The scoring app relied on the RDWatch  ModelRunDetailSchema which included the alias.  Adding that alias to the queries in the Scoring app fixed the issue.
https://github.com/ResonantGeoData/RD-WATCH/blob/model-run-region/django/src/rdwatch/views/model_run.py#L112
Additionally, the proposal when selecting one had a need to know the region and it referenced the ModelRun region relationship differently.  I've updated it so it will reference the proper name field.
> update scoring and proposals to handle new model-run region relationship

- django/src/rdwatch_scoring/views/model_run.py
- django/src/rdwatch_scoring/views/vector_tile.py
- vue/src/components/LayerSelection.vue
- vue/src/components/imageViewer/ImageViewer.vue
- vue/src/mapstyle/rdwatchtiles.ts
List of minor changes to fix small issues:
- Proposal Query need the 'region_name' instead of 'region' returned
- The model-run endpoints for getting the values required a `proposal` parameter.  We wanted it to be an optional parameter with the default value of `None`.  WIthout this the default /scoring view would break.
- Within ImageViewer I made the SAM icon dependent on it not being within scoring because there are no implemented features of SAM in the scoring app yet.
- rdwatchtiles.ts - the built query string was incorrect, it didn't properly handle the 'randomKey' and also didn't include the 'year' for our year filtering.  I've quickly improved how it generates the query so it should be better for any combination of `proposal, randomKey, year`
- In the vector tile creation I needed …
> Scoring Proposal Changes

- django/src/rdwatch/views/site_evaluation.py
We have to go through the model run to get the region name now.
> Fix crash on site model JSON download endpoint

- django/src/rdwatch/server/settings.py
- django/src/rdwatch/tasks/__init__.py
- django/src/rdwatch/tests/test_model_runs.py
This PR consolidates the two existing "garbage collection" tasks (cleaning up old model runs + annotation exports) into one task, and also adds scheduled cleanup of Satellite fetches that are over a day old.
> Auto delete old satellite fetches

- django/src/rdwatch/views/model_run.py
- vue/src/client/services/ApiService.ts
- vue/src/components/ModelRunDetail.vue
Fixes the issue where model-run downloading for proposals wasn't working because using a single parameter query at the end of a trailing slash in ninja wasn't being interpreted properly.
> download model-run endpoint fix

- tileserver/package-lock.json
- tileserver/package.json
I forgot to do this in https://github.com/ResonantGeoData/RD-WATCH/pull/407
> Bump node package version

- .gitignore
Sometimes this file appears in the root for me.
> gitignore `celerybeat-schedule.*` files

- Dockerfile
The `/api/status` endpoint in the AWS deployment currently returns `"rdwatch_version": "unknown"` for the version. Looking at the logs, it looks like [this subprocess](https://github.com/ResonantGeoData/RD-WATCH/blob/main/django/src/rdwatch/server/settings.py#L19) call to `git` is failing with 
```
fatal: detected dubious ownership in repository at '/app'
To add an exception for this directory, call:
git config --global --add safe.directory /app
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/usr/local/lib/python3.11/subprocess.py", line 466, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
raise …
```
> Fix version display in AWS deployment

- .github/workflows/cd.yaml
After deploying #419, it now says
`fatal: No names found, cannot describe anything.`
When trying to get the version git tag. The `checkout` action doesn't fetch tags by default, so the `.git` directory getting copied into the docker image won't have them.
> Fetch git tags in docker build action

- .github/workflows/ci.yaml
- dev/.env.docker-compose-native
- docker-compose.override.yaml
- docker-compose.yaml
This PR configures celery to use the existing redis instance (the one used for caching) for queueing instead of provisioning a separate RabbitMQ instance.
@BryonLewis I applied this change to the rgd-dev instance as well, if you'd like to verify that as well.
> Switch to Redis for task queue

- django/src/rdwatch/schemas/site_model.py
This PR fixes some issues I noticed while debugging the bug David reported about 500 errors on model run upload.
- After #407, new performers can be created. But, the pydantic validation for site/region models still restricts the list of accepted performers. 
- If an invalid geojson polygon is provided, GeoDjango throws a `GEOSException`. We don't explicitly catch it currently, resulting in a 500 error.
> Misc fixes/improvements to ingest endpoint

- django/src/rdwatch/admin.py
- django/src/rdwatch/views/model_run.py
- django/src/rdwatch_scoring/views/model_run.py
- vue/src/client/models/ModelRun.ts
- vue/src/client/services/ApiService.ts
- vue/src/components/LayerSelection.vue
- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
- vue/src/components/annotationViewer/AnnotationList.vue
- vue/src/components/siteList/SiteList.vue
- vue/src/components/siteList/SiteListCard.vue
- vue/src/store.ts
resolves #418 
- May be a slight performance penalty but I think it's better to have non-groundtruth provide a direct link to the ground truth so it can be used to toggle on/off.
- The linked groundtruth will be the matching region with `ground_truth=True` with the newest date.
- The ground truth is not shown by default and instead in RDWatch it will link to ground truth when you turn it on using the Layer buttons.
- The groundtruth and model for the layer selections will enable/disable automatically based on the selected model.  So groundtruth is inherently connected to the model-run instead of having to be toggled automatically.
- Updated the scoring response to label ground-truth vs the regular items respectively in the list.
- Updated the regular RDWatch response to label groundtruth …
> GroundTruth Refactor

- vue/src/client/services/ApiService.ts
- vue/src/components/LayerSelection.vue
- vue/src/components/annotationViewer/AddProposal.vue
- vue/src/components/annotationViewer/AnnotationList.vue
- vue/src/components/annotationViewer/SideBar.vue
- vue/src/interactions/editPolygon.ts
- vue/src/store.ts
- vue/src/views/AnnotationViewer.vue
resolves #427 
- Adds button in proposal mode to create Site Proposals
- When clicked it opens a side panel that has instructions about drawing a polygon
- User can draw the polygon and then edit the metadata such as time, label, comments and siteId number.
- Added in the ability to turn on regional satellite images for proposal view for drawing new annotations.
- Updated the proposal view to add in the satellite timestamps so that a satelliteview can be used when drawing new proposals.
https://github.com/ResonantGeoData/RD-WATCH/assets/61746913/473f6d4d-a27d-4cbe-9ff2-0f0704e718c6
> Creating Site Proposals

- rdwatch/scoring/router.py
The refactor changed the scoring `app_label` to `scoring` so this required the `ScoringRouter` to be updated to match the new name.
> ScoringDB Router fixing

- rdwatch/core/views/model_run.py
- scripts/loadModelRun.py
simple change to describe what is going on where clients that aren't logged in cannot upload new models.
Our upload models script will check to see if a ModelRun already exists.  It does this by requiring access to the GET /model-runs endpoint.
Our CRSFExempt utilizing the RDWATCH-API-KEY doesn't account for this so it will fail.
This PR is just meant as a draft to show a quick solution to the issue and not intended to be merged in.
> Get ModelRuns using RDWATCH Api Key

- .github/workflows/ci.yaml
This will cause CI to fail if the docs build fails.
> Build docs in CI

- docker-compose.override.yaml
In particular, this makes the full docker-compose dev env build correctly on M1 Macs.
> Fix docker configuration for ARM CPUs

- .github/workflows/cd.yaml
- docs/requirements.txt
The mkdocs github action has support for a 'requirements.txt' for any additional dependencies that are needed for mkdocs:
https://github.com/mhausenblas/mkdocs-deploy-gh-pages?tab=readme-ov-file#installing-mkdocs-plugins
We utilize a materials icon plugin so it can render some of the icons I am using currently in the documentation.
The Error from deploying docs github actions log:
I forked the Repo and applied the test on my own and it seems to to work: https://bryonlewis.github.io/RD-WATCH/
> Fix Docs Deployment

- rdwatch/core/fixtures/lookups.json
Adds the iMerit performer to the lookups to support ground truth annotations.  The validator looks like the following:
```
@validator('originator')
def validate_originator(cls, v: str) -> str:
if Performer.objects.filter(short_code=v.upper()).exists():
return v
raise ValueError(f'Invalid originator "{v}"')
```
The `v.upper` is why I'm using IMERIT as the short code.
> adds iMerit to lookups

- Dockerfile
- vue/src/App.vue
- vue/src/client/models/ServerStatus.ts
- vue/src/components/SideBar.vue
- vue/src/store.ts
- Populate versioning info in the docker build for prod and dev
- Show the version in the UI
The dev build will still show `0.0.0dev0` because `/app/rdwatch/__init__.py` doesn't exist in the docker container at build time (and it gets mounted over anyways). I verified that the prod docker image has a populated `__init__.py`, but haven't tried running it yet. Installing `poetry-dynamic-versioning` and running `poetry dynamic-versioning` will update the version info.
> Add versioning info

- .github/workflows/cd.yaml
`poetry-dynamic-versioning` requires a full checkout of the repo to determine the version string.
> Do a full checkout in docker image build

- rdwatch/core/tasks/__init__.py
- rdwatch/core/utils/images.py
- rdwatch/core/utils/worldview_nitf/raster_tile.py
- rdwatch/core/utils/worldview_nitf/satellite_captures.py
- rdwatch/core/utils/worldview_nitf/stac_search.py
- rdwatch/core/views/site_observation.py
- vue/src/client/services/ApiService.ts
- vue/src/components/ImagesDownloadDialog.vue
This PR adds support for downloading WorldView NITF imagery. 
On the STAC server, NITFs are stored in the `worldview-nitf` collection. I created a new module, `rdwatch.core.utils.worldview_nitf`, that mirrors the existing `rdwatch.core.utils.worldview_processed` with a few key differences:
1) I removed pan-sharpening logic from `worldview_nitf`.
2) `rio-tiler` gets stuck indefinitely if you give it an S3 URL to a NITF file directly. I assume it's struggling with the size somehow, as obviously unlike COGs it must download the entire image (on the order of gigabytes) every time it wants to chip out a small bounding box. To get around this, I download the NITF image from S3 directly using boto3 to a temporary file and pass `rio-tiler` the path to that, and it works.
3) Following on from 2), …
> Preliminary support for  WorldView NITF imagery

- rdwatch/core/models/site_observation.py
The presence of any null-valued timestamps broke the rendering of the site observation admin page. More generally it would break any place we call the `__str__` method on such a site observation.
> Fix site observation admin 500 error

- vue/src/views/SmartFlow.vue
An additional error I noticed when reviewing code.
The Smartflow integration is experimental and in early stages right now.  In the future if we continue down this path (Not guaranteed) I would suggest updating the types for the responses, but for right now, I believe disabling the typescript warning is fine.
> DAG Typescript Warning

- rdwatch/core/admin.py
The Satellite Fetching admin page was emitting tens of thousands of SQL queries when loading, even though my system contained zero satellite fetching records.
The reason for this was the `list_filter` on the `site` attribute, which was causing a SQL query for each SiteEvaluation that exists in the database to be issued.
Additionally, there was a similar issue when loading the Add satellite fetching page in django-admin, which was fixed by making `site` use the `raw_id` field behavior.
> Fix query explosion problem in django-admin

- dev/airflow_sample_dag.py
- rdwatch/core/schemas/region_model.py
- rdwatch/core/schemas/site_model.py
Updating the region_id constraint in the single schema would only allow for custom region names when creating a model run.  Other portions of the code utilize the region_id constraint.
- The DAG support is relatively new and may not be used in the future, but I figured I should update it.
- The SiteSummaryFeature is used during the creation of a region from a geoJSON and checks inside of it the region_id.  This constraint also needs to be relaxed.
- The SiteFeature was a base tool for importing sites and observations in the system.  Allowing it to have a custom name means that all geoJSON files can now have unconstrained names as well.  (They are limited to the siteID being a name followed by an underscore and 4 or 8 digits.
- We returned back the site_id number before using a slice of …
> additional modifications to support region constraint relaxation

- dev/airflow_sample_dag.py
- rdwatch/core/schemas/region_model.py
- rdwatch/core/schemas/site_model.py
- rdwatch/core/views/model_run.py
Fixes #484
For now I've just made the region name accept any non-empty string that fits in the database column. Let me know if that's not constrained enough.
> Relax name restrictions on model run region names

- rdwatch/core/utils/raster_tile.py
- rdwatch/scoring/views/model_run.py
- vue/src/client/services/ApiService.ts
- vue/src/components/siteList/SiteList.vue
- vue/src/components/siteList/SiteListCard.vue
Previously the Site List while in scoring mode and looking at the simple or detailed views wouldn't display the ground truth in the list.
Updates:
- Makes sure the simple/detailed scoring views don't filter out the ground truth
- Adds to the backend the color_code data for each site.  This may be an expensive operation in comparison to not having it
- Handles filtering the sites in the list based on the simple/detailed display properties in the annotation colors
- Adds an X/Y (x out of y) to the site list to indicate how many sites are displayed out of the total number of sites.
https://github.com/user-attachments/assets/aab4a00c-b454-4e5d-9bf6-7dab45bae282
> Enable Ground Truth List for Simple/Detailed views

- vue/src/components/ImagesDownloadDialog.vue
Now that WV cog is disabled, we should default to S2 instead of WV nitf.
> Default to S2 imagery download

- rdwatch/core/schemas/region_model.py
Matches the [SiteModel originator validation logic](https://github.com/ResonantGeoData/RD-WATCH/blob/65d54aebee3be6ba418830aaa8bd358889d22466/rdwatch/core/schemas/site_model.py#L56).
> Validate the RegionModel performer against the db

- rdwatch/core/admin.py
Similar to #478, each site image is issuing an additional query for its associated evaluation, and also N queries for each of the N observations associated with that evaluation. This leads to a N+1 query explosion that makes the `SiteImage` admin unusable.
> Fix query explosion for `SiteImage` admin page

- rdwatch/core/schemas/region_model.py
- rdwatch/core/schemas/site_model.py
Remove the originator validators. These validators only validated that the originator exists in the database, and did so for every Feature that has an `originator` field, which could lead to many DB queries.
See #498 for an alternative to these validators.
> Remove originator validators

- vue/src/components/SideBar.vue
- vue/src/components/annotationViewer/SideBar.vue
The removal of the `@update:timeRang` from `SideBar.vue` meant that the slider was always going to utilize the UNIX epoch time.  This uses the global `state.timeMin`.  I think this was an oversight of mine when I was converting the very heavily integrated component system signaling (where it was doing some passing up/down of information) into more of a store system when I came on to the project.
I do understand that our Store is really overloaded right now and at some point should probably be refactored but that is an issue for another time.
> set timeMin to modelRun list timeMin

- vue/src/client/models/ModelRunList.ts
- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
- vue/src/components/annotationViewer/AnnotationList.vue
- vue/src/components/annotationViewer/SideBar.vue
- vue/src/components/siteList/SiteList.vue
- vue/src/store.ts
- `loadModelRuns` is now part of the store as `queryModelRuns` and updates store state.
- `queryModelRuns` manages pagination state through "firstPage" and "nextPage" requests (see ModelRunList.vue for usage).
- `checkDownloading` is now part of the store as `refreshModelRunDownloadingStatuses`. Additionally, it has been fixed to properly update the downloading statuses of all loaded pagination pages.
- A side note: I have yet to test this function!
- All usages of `state.downloadCheck` have been replaced with calls to `refreshModelRunDownloadingStatuses`.
> Refactor loadModelRuns to the store as a global action

- poetry.lock
- pyproject.toml
- rdwatch/core/views/server_status.py
Updates the version string in the UI to be more user friendly.
Tagged release versions now look like this:
And pre-release versions remain the same:
> Cleaner version display format

- rdwatch/core/tasks/__init__.py
- rdwatch/core/utils/capture.py
- rdwatch/core/utils/images.py
- rdwatch/core/utils/raster_tile.py
- rdwatch/core/utils/satellite_bands.py
- rdwatch/core/utils/stac_search.py
- rdwatch/core/utils/worldview_nitf/satellite_captures.py
- rdwatch/core/utils/worldview_processed/satellite_captures.py
- rdwatch/core/views/satellite_image.py
- rdwatch/scoring/tasks/__init__.py
- vue/src/components/ImagesDownloadDialog.vue
- `stac_search.py` and `satellite_bands.py`: Switch to using the pystac_client.ItemSearch interface directly
- `satellite_bands.py`: Modified `get_bands()` and the `Bands` type to be a STACCapture
- `raster_tile.py`: refactored get_raster_tile/bbox to accept a reader
- `raster_tile.py`: Removed "b1" key in favor of picking the first band
- This is a point of discussion for multichannel images!
- `capture.py`: abstracted captures to have an `open_reader()` method for generic rio_tiler reader usage
> L8 satellite images

- rdwatch/allauth.py
- rdwatch/core/tasks/__init__.py
- rdwatch/core/tasks/animation_export.py
- rdwatch/core/utils/raster_tile.py
- rdwatch/core/utils/worldview_nitf/raster_tile.py
- rdwatch/core/utils/worldview_processed/raster_tile.py
- rdwatch/scoring/tasks/__init__.py
This is a prerequisite to configuring Sentry, since `WARNING` logs will set off an issue alert there. 
We may want to go back through and figure out if some of these can be removed, or at least downgraded to `DEBUG` logs. But this change will at least allow us to hook up our deployment to Sentry without blowing it up with issues.
> Change WARN logs to INFO where needed

- poetry.lock
- pyproject.toml
- rdwatch/core/apps.py
- rdwatch/settings.py
Installs `sentry_sdk` and adds necessary configuration to Django app. Based in large part on https://github.com/kitware-resonant/django-composed-configuration/blob/master/composed_configuration/_sentry.py and https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/apps.py
Related infrastructure PR: https://smartgitlab.com/kitware/rgd_aws_infrastructure/-/merge_requests/16
> Configure sentry for Django application

- Dockerfile
- docker/nginx.json
- rdwatch/settings.py
This adds a step to the Dockerfile to run `collectstatic` to build all Django static files and updates the nginx config to serve them. 
This supersedes #460. See that PR description/comments for the motivations behind this PR
> Serve Django static files with nginx unit

- rdwatch/core/tasks/__init__.py
- rdwatch/core/views/model_run.py
- vue/src/client/services/ApiService.ts
- vue/src/components/ModelRunList.vue
- vue/src/components/UploadModelRun.vue
- Report errors to the client
- allow for zip files to not have region models if an override region is specified
- list regions and performers in their respective dropdowns in the upload box
> Improve upload flow

- rdwatch/core/utils/stac_search.py
The L8 STAC server returns incorrect pagination links when using GET search queries.
> Use POST when querying the STAC server

- rdwatch/core/utils/images.py
I think the lowercase cog and nitf made me replace that with the 'wv' instead of 'WV' when we did the emergency switch to Element84.
> worldview NITF fix

- rdwatch/scoring/views/satellite_fetching.py
This fixes https://kitware-data.sentry.io/issues/6029101458/?alert_rule_id=15484485&alert_timestamp=1730232466058&alert_type=email&environment=rgdtedev&notification_uuid=511df48d-a61e-49d2-8472-831143d5b282&project=4508054265724928&referrer=alert_email
> Fix crash due to missing `error` key

- rdwatch/core/apps.py
I thought I enabled Sentry performance tracking in #512, but it turns out I did that incorrectly. This PR fixes it, and also adds an exception for the `/sites` endpoint that we're currently seeing 504 errors on.
Since we have a monthly quota for how many traces we can send to Sentry, it's usually necessary to configure `sentry_sdk` to only send performance data for a subset of all requests. I've configured it so that for any general request, it has a 5% chance of being recorded by Sentry Performance, _unless_ it's in the `priority_routes` list (in which case, it has a sample rate of 100%, i.e. it will always be recorded).
I've built and deployed this image to the AWS deployment, so you can see some sample traces already in Sentry …
> Enable Sentry performance tracking

- DEVELOPMENT.md
- docs/DevDocs/GettingStarted.md
- docs/DevDocs/IngestingData.md
`--rm_dir` is now `--rm_path`.
> Update metrics CLI invokation in dev docs

- rdwatch/scoring/views/model_run.py
Moves the color_code subquery to a separate query to avoid a slow subquery in the main query, due to the
EvaluationBroadAreaSearchDetection table being extremely large. The number of sites in an evaluation run is small enough that it's feasible to load the site_id->color_code mapping into memory and manually join it with the sites_list in Python.
> Optimize sites list query

- docker-compose.yaml
Existing deployment databases (postgresql v16) are not compatible with postgresql v17. Pin to v16 so we don't become incompatible with existing databases if the docker image gets deleted and re-downloaded.
> Pin postgis docker version

- vue/src/actions/localMapLayers.ts
- vue/src/actions/map.ts
- vue/src/components/LocalLayers.vue
- vue/src/components/MapLibre.vue
- vue/src/components/SideBar.vue
- vue/src/components/annotationViewer/AnnotationList.vue
- vue/src/mapstyle/index.ts
- vue/src/mapstyle/localgeojson.ts
- vue/src/store.ts
- vue/src/utils.ts
- vue/src/views/RGD.vue
Users can now visualize local geojson files in RD-WATCH.
[Screen Recording 2024-10-22 at 3.19.43 PM.webm](https://github.com/user-attachments/assets/292e3f1a-be57-4b3b-890c-b89e194b667c)
Nice-to-haves and other considerations:
* toggle layer visibility
* nicer layer names (based on what?)
* edit geometry styles
* should the annotator view also support viewing local geojsons?
Other changes:
* The map is no longer partially covered by the sidebar
* An event is used for triggering `map.fitBounds()` instead of a state variable
* minor whitespace changes that were automatically done by my editor
> Allow for viewing local geojson layers

- vue/src/views/RGD.vue
The image viewer was being pushed beyond the viewport with the recent map-layer CSS changes introduced in #524.
> Fix image viewer not showing up

- rdwatch/core/tasks/animation_export.py
- rdwatch/scoring/views/satellite_fetching.py
If a site image has an associated site observation, show the site observation's date. Otherwise, show "-obs".
A sample screenshot is provided below. (The observation date is arbitrary and not indicative of real data.)
> Show site observation date in export

- rdwatch/core/tasks/animation_export.py
- rdwatch/scoring/tasks/animation_export.py
- vue/src/client/services/ApiService.ts
- vue/src/components/animation/AnimationDownloadDialog.vue
- vue/src/components/imageViewer/ImageFilter.vue
- vue/src/components/imageViewer/ImageViewer.vue
- vue/src/components/imageViewer/imageUtils.ts
- vue/src/store.ts
A new UI element, "line thickness factor", provides users with the means to adjust the polygon line thickness in both the viewer and the animation export.
Other changes:
- show the point size slider in the animation dialog
- sync the point size + rescale parameters to the animation dialog
New line width controls:
> Image viewer line thickness

- vue/src/components/ImagesDownloadDialog.vue
- vue/src/components/ModelRunCard.vue
- vue/src/components/SideBar.vue
- vue/src/components/annotationViewer/SideBar.vue
- vue/src/components/siteList/SiteListCard.vue
Synchronizes some differences with icons that were being used and updated language to refer to fetching image chips vs downloading satellite images.
> Synchronizes Icons and update Language from Downloading to Fetching

- rdwatch/core/views/site_observation.py
- rdwatch/scoring/views/site_observation.py
Attempting to return *any* exception as a JSON response will result in a `Object of type WorkerLostError is not JSON serializable` error.
Fixes https://kitware-data.sentry.io/issues/6078296720/?project=4508054265724928&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=1
> Fix json serialization error

- vue/src/components/LocalLayers.vue
- vue/src/components/ModelRunList.vue
- vue/src/components/SideBar.vue
- vue/src/components/TimeSlider.vue
- vue/src/components/annotationViewer/SideBar.vue
- vue/src/index.css
- vue/src/views/AnnotationViewer.vue
- vue/src/views/RGD.vue
I noticed that scrolling long model lists and local layers is broken. Updated CSS to properly scroll on those long lists.
The changes in `SideBar.vue` look extensive, but in reality I only modified some classes and nested all of the elements from `<mode-selector />` to `<EvalFilter />` in a `<div class="flex-grow-0">`.
> Fix scrolling model lists and local layers

- vue/src/views/AnnotationViewer.vue
When testing the SAM stuff I noticed the image viewer wasn't coming up.  This is related to #543.  Added code so that in Annotator Mode the image viewer will display when selecting a site.
> fixes display of image-viewer in annotator mode

- vue/src/components/TimeSlider.vue
The TimeSlider component is cut off visually on the left side.
Before:
After:
> Fix TimeSlider being cut off visually

- rdwatch/scoring/views/vector_tile.py
- vue/src/client/services/ApiService.ts
- vue/src/components/siteList/SiteList.vue
- vue/src/mapstyle/annotationStyles.ts
- vue/src/mapstyle/rdwatchtiles.ts
- vue/src/store.ts
This removes the expensive `color_code` subquery and adds a new endpoint that returns the color mapping by itself. The endpoint is cached, but even on cache misses it is much faster than the previous method.
I've updated the client to handle this new approach. This required reworking how the color_code MapLibre filter worked quite a bit.
> Optimize scoring vector tiles

- rdwatch/core/tasks/animation_export.py
- rdwatch/scoring/tasks/animation_export.py
- vue/src/components/animation/AnimationDownloadDialog.vue
- vue/src/components/imageViewer/ImageFilter.vue
- vue/src/components/siteList/SiteList.vue
- Allow line thickness to apply to scoring/core animation exporting
- Increase the line thickness range
- Increase the circle point radius
- Fix an error with the color_code being called when not in the scoring mode causing an error.
> Update Circle Thickness, extend thickness/point size range, fix Scoring coloring

- rdwatch/scoring/tasks/animation_export.py
This mimics #538 but for the scoring app.
> Fix scoring not exporting the last observation date

- rdwatch/scoring/views/model_run.py
- vue/src/client/services/ApiService.ts
- vue/src/components/siteList/SiteList.vue
- vue/src/components/siteList/SiteListCard.vue
- vue/src/interactions/mouseEvents.ts
I missed some of this in #553. Also, I realized we don't even need to embed the `color_code` in the `/sites/` endpoint response anymore, since we now have the color code mapping endpoint that gets stored in the global Vue state.
> Remove color_code from /sites/ endpoint, update client

- rdwatch/core/apps.py
Setting this to WARNING causes to many extraneous logs to be reported as issues in Sentry. `rio_tiler` in particular is very noisy, and it's difficult to calibrate things because we have no control over the source data its processing.
> Configure sentry logging integration for ERROR logs only
